# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
image:
  name: mhimmercocha/node
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD
  email: $DOCKERHUB_EMAIL

pipelines:
  custom:
    deploy-to-development:
      - step:
          name: Deploy to development
          deployment: test
          script:
            - cocha-deployApi -a payment -e development -c `git rev-parse --short $BITBUCKET_COMMIT`
    deploy-to-qa:
      - step:
          name: Deploy to QA
          deployment: staging
          script:
            - cocha-deployApi -a payment -e qa -c `git rev-parse --short $BITBUCKET_COMMIT`
    deploy-to-production:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - cocha-deployApi -a payment -e production -c `git rev-parse --short $BITBUCKET_COMMIT`
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm i
#            - npm run lint
      # - step:
      #     name: Sending code to Sonarqube
      #     caches:
      #       - node
      #     script:
      #       - npm run sonar
      - step:
          name: Deploy to Development
          deployment: test
          script:
            - cocha-deployApi -a payment -e development -c `git rev-parse --short $BITBUCKET_COMMIT`
      - step:
          name: Deploy to QA
          deployment: staging
          script:
            - cocha-deployApi -a payment -e qa -c `git rev-parse --short $BITBUCKET_COMMIT`
